# -*- coding: utf-8 -*-
"""Chart copy in both languages. Key -> (English, Spanish).
Placeholders use {} and are filled by charts.T(key, *args)."""

MONTHS = {'en':['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
          'es':['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']}

TX = {
# ---- c01 ----
'c01.t':('We ship on the quarter, the consumer buys at Christmas',
         'Nosotros embarcamos en el cierre de trimestre; el consumidor compra en Navidad'),
'c01.s':('Seasonal index, own-year average = 100. Sell-in 2024-2025, EPOS 2025. Excludes Gucci Fragrance Multiline.',
         'Índice estacional, promedio del propio año = 100. Sell-in 2024-2025, EPOS 2025. Excluye Gucci Fragrance Multiline.'),
'c01.y':('Index (100 = average month)','Índice (100 = mes promedio)'),
'c01.l1':('Sell-in (what we ship)','Sell-in (lo que embarcamos)'),
'c01.l2':('EPOS (what the consumer buys)','EPOS (lo que compra el consumidor)'),
'c01.a1':('Sell-in peaks\nMar / Jun / Sep','El sell-in pica\nMar / Jun / Sep'),
'c01.a2':('Consumer peaks\nin December','El consumidor pica\nen diciembre'),
# ---- c02 ----
'c02.t':('The three quarter-end peaks repeat year on year',
         'Los tres picos de cierre de trimestre se repiten año con año'),
'c02.s':('Sell-in seasonal index computed separately for each calendar year.',
         'Índice estacional de sell-in calculado por separado para cada año calendario.'),
'c02.n':('Mar / Jun / Sep repeat in both years','Mar / Jun / Sep se repiten en ambos años'),
# ---- c03 ----
'c03.t':('Sell-in leads consumer offtake by about three months',
         'El sell-in se adelanta al consumo unos tres meses'),
'c03.s':('Best-fitting lag per product line, {} lines with a usable EPOS signal. Volume-weighted mean {} months.',
         'Lag de mejor ajuste por product line, {} líneas con señal EPOS utilizable. Media ponderada por volumen: {} meses.'),
'c03.y':('Product lines','Product lines'),
'c03.x':('{} mo','{} m'),
'c03.a':('most common:\nsell-in leads by\n3 months','lo más común:\nel sell-in se adelanta\n3 meses'),
# ---- c04 ----
'c04.t':('A launch front-loads: month 0 is 2.7x a normal month',
         'El lanzamiento se carga al frente: el mes 0 es 2.7x un mes normal'),
'c04.s':('{} launches since 2023.M09, aligned on their first shipment. Index: year-1 average month = 100.',
         '{} lanzamientos desde 2023.M09, alineados en su primer embarque. Índice: mes promedio del año 1 = 100.'),
'c04.y':('Index (year-1 avg month = 100)','Índice (mes prom. año 1 = 100)'),
'c04.r':('year-1 average month','mes promedio del año 1'),
'c04.a':('launch month =\n{}x an average month','mes de lanzamiento =\n{}x un mes promedio'),
# ---- c05 ----
'c05.t':('We fill the pipe in month 0; the consumer arrives in month 3',
         'Llenamos el pipe en el mes 0; el consumidor llega en el mes 3'),
'c05.s':('Both series indexed to their own 12-month average = 100, so they share one axis.',
         'Ambas series indexadas a su propio promedio de 12 meses = 100, para compartir un solo eje.'),
'c05.y':('Index (own 12-month avg = 100)','Índice (prom. 12 meses propio = 100)'),
'c05.l1':('Sell-in','Sell-in'),
'c05.g':('3 months','3 meses'),
# ---- c06 ----
'c06.t':('Service collapses exactly when the launch starts selling through',
         'El servicio colapsa justo cuando el lanzamiento empieza a venderse'),
'c06.s':('Demand lost to supply cuts = cuts / (actuals + cuts), pooled across launches. Colour = service status; value labelled on every bar.',
         'Demanda perdida por supply cuts = cuts / (actuals + cuts), agrupado entre lanzamientos. Color = estado de servicio; valor en cada barra.'),
'c06.y':('Demand lost (%)','Demanda perdida (%)'),
'c06.a':('the consumer is buying here','aquí es cuando compra el consumidor'),
# ---- c07 ----
'c07.t':('We run out of stock in our own peak months',
         'Nos quedamos sin inventario en nuestros propios meses pico'),
'c07.s':('Demand lost to supply cuts by calendar month, 2024.M01-2026.M07. Colour = service status; value labelled on every bar.',
         'Demanda perdida por supply cuts por mes calendario, 2024.M01-2026.M07. Color = estado de servicio; valor en cada barra.'),
'c07.a':('sell-in peak','pico de sell-in'),
# ---- c08 ----
'c08.t':('Two houses carry almost all of the service loss',
         'Dos houses concentran casi toda la pérdida de servicio'),
'c08.s':('Demand lost to supply cuts, 2025.M01-2026.M07. Colour = service status; every bar carries its value.',
         'Demanda perdida por supply cuts, 2025.M01-2026.M07. Color = estado de servicio; cada barra lleva su valor.'),
# ---- c09 ----
'c09.t':('The forward book is aggressive near-in and empties out after 2027',
         'El forward book es agresivo en el corto plazo y se vacía después de 2027'),
'c09.s':('Average monthly Consensus - Final vs the last 12 closed months of actuals. Labels show % of run rate.',
         'Consensus - Final promedio mensual vs los últimos 12 meses cerrados de actuals. Las etiquetas muestran % del run rate.'),
'c09.y':('Units per month','Unidades por mes'),
'c09.r':('current run rate','run rate actual'),
'c09.x':(['2026\n(Aug-Dec)','2027','2028','2029\n(Jan-Jul)'],
         ['2026\n(Ago-Dic)','2027','2028','2029\n(Ene-Jul)']),
# ---- c10 ----
'c10.t':('One unit in three of the forward book has no visible origin',
         'Una de cada tres unidades del forward book no tiene origen visible'),
'c10.s':('Layers as a share of the 2026.M08-2029.M07 consensus (20.2M units). Every bar is labelled.',
         'Capas como porcentaje del consensus 2026.M08-2029.M07 (20.2M unidades). Cada barra está etiquetada.'),
'c10.x':('% of the forward Consensus - Final','% del Consensus - Final futuro'),
'c10.res':('Not traceable to any layer','Sin origen en ninguna capa'),
# ---- c11 ----
'c11.t':('Only 7% of your volume sits on genuinely stable codes',
         'Solo el 7% de tu volumen está en códigos realmente estables'),
'c11.s':('Archetype by volume share. CV = month-to-month volatility; higher means harder to forecast.',
         'Arquetipo por participación de volumen. CV = volatilidad mes a mes; más alto es más difícil de pronosticar.'),
'c11.x':('% of last-12-month volume','% del volumen de los últimos 12 meses'),
'c11.n':(['Stable & Repeatable','Moderate','Declining','Lumpy / Event-Driven','New / Launch','Intermittent'],
         ['Estable y repetible','Moderado','En declive','Irregular / por evento','Nuevo / lanzamiento','Intermitente']),
'c11.f':('{}  ({} lines, CV {})','{}  ({} líneas, CV {})'),
# ---- c12 ----
'c12.t':('Every house has a different calendar','Cada house tiene un calendario distinto'),
'c12.s':('Sell-in seasonal index, 100 = own average month. Blue below 100, red above; numbers printed in every cell.',
         'Índice estacional de sell-in, 100 = mes promedio propio. Azul bajo 100, rojo encima; el número va en cada celda.'),
# ---- c13 ----
'c13.t':('Half your volume sits in a handful of codes',
         'La mitad de tu volumen está en un puñado de códigos'),
'c13.s':('Cumulative share of the last 12 closed months, product lines ranked by volume. Excludes Gucci Fragrance Multiline.',
         'Participación acumulada de los últimos 12 meses cerrados, product lines ordenadas por volumen. Excluye Gucci Fragrance Multiline.'),
'c13.y':('Cumulative % of volume','% acumulado del volumen'),
'c13.x':('Product lines, ranked by volume','Product lines, ordenadas por volumen'),
'c13.a':('{} lines = {} of volume','{} líneas = {} del volumen'),
# ---- c14 ----
'c14.t':('ULTA and the rest do not peak in the same months',
         'ULTA y el resto no pican en los mismos meses'),
'c14.s':('Sell-in seasonal index by customer group, 2024-2025. 100 = own average month.',
         'Índice estacional de sell-in por customer group, 2024-2025. 100 = mes promedio propio.'),
# ---- c15 ----
'c15.t':('Where the forward book needs a human this month',
         'Dónde el forward book necesita una persona este mes'),
'c15.s':('Volume carried by each risk flag. A line can carry more than one flag.',
         'Volumen que carga cada bandera de riesgo. Una línea puede tener más de una bandera.'),
'c15.x':('Units at stake (last 12 closed months)','Unidades en juego (últimos 12 meses cerrados)'),
'c15.f':('{} lines · {}K u','{} líneas · {}K u'),
'c15.n':({'SERVICE-LOSS':'Service Loss','LOST-FORECAST':'Lost Forecast','CONSUMER-DECLINE':'Consumer Decline',
          'OVER-BOOKED':'Over Booked','UNDER-BOOKED':'Under Booked','HORIZON-CLIFF':'Horizon Cliff',
          'PHANTOM-FORECAST':'Phantom Forecast'},
         {'SERVICE-LOSS':'Pérdida de servicio','LOST-FORECAST':'Forecast perdido','CONSUMER-DECLINE':'Consumo en caída',
          'OVER-BOOKED':'Sobre-cargado','UNDER-BOOKED':'Sub-cargado','HORIZON-CLIFF':'Corte de horizonte',
          'PHANTOM-FORECAST':'Forecast fantasma'}),
# ---- c16 ----
'c16.t':('The codes where shipments and consumer demand disagree',
         'Los códigos donde el embarque y la demanda del consumidor no coinciden'),
'c16.s':('Bubble area = volume. Points above the dashed line ship faster than the consumer buys.',
         'Área de la burbuja = volumen. Los puntos sobre la línea punteada embarcan más rápido de lo que compra el consumidor.'),
'c16.x':('EPOS growth, last 6m vs prior 6m (%)','Crecimiento EPOS, últimos 6m vs 6m previos (%)'),
'c16.y':('Sell-in growth, last 6m vs prior 6m (%)','Crecimiento sell-in, últimos 6m vs 6m previos (%)'),
'c16.d':('shipping = selling','embarque = venta'),
'c16.q1':('shipping into inventory','embarque a inventario'),
'c16.q2':('under-shipping demand','embarque por debajo\nde la demanda'),
# ---- c17 ----
'c17.t':('43% of your volume sits on codes the system cannot forecast well',
         'El 43% de tu volumen está en códigos que el sistema no pronostica bien'),
'c17.s':('Forecastability score built from volatility, continuity, year-on-year repeatability, history depth and EPOS visibility.',
         'Score de pronosticabilidad construido con volatilidad, continuidad, repetibilidad año contra año, profundidad de historia y visibilidad de EPOS.'),
'c17.f':('{}  ({} lines)','{}  ({} líneas)'),
'c17.n':({'HIGH':'HIGH','GOOD':'GOOD','FAIR':'FAIR','LOW':'LOW'},
         {'HIGH':'ALTA','GOOD':'BUENA','FAIR':'REGULAR','LOW':'BAJA'}),
# ---- c18 ----
'c18.t':('Gucci Fragrance Multiline is not a product, it behaves like a batch',
         'Gucci Fragrance Multiline no es un producto, se comporta como un lote'),
'c18.s':('Monthly sell-in of the excluded catch-all line, 2023.M08-2026.M07.',
         'Sell-in mensual de la línea agrupadora excluida, 2023.M08-2026.M07.'),
'c18.y':('Units','Unidades'),
'c18.a':('{} units in one month\n= 11x its own median month',
         '{} unidades en un solo mes\n= 11x su propio mes mediano'),
}
